---
title: "Geohash graph NNs study"
author: Anton Antonov
date: 2024-07-01
output: html_notebook
---


```{r setup}
library(RouteSystemRecommender)
library(SMRMon)
library(dplyr)
library(purrr)
library(leaflet)
library(geohashTools)
library(igraph)
```

Read a data frame with coordinates of ZIP codes:

```{r}
dfZIPs <- read.csv("https://raw.githubusercontent.com/antononcube/SystemModeling/master/Data/dfUSZipCodesFrom2013GovernmentData.csv",  colClasses = c("character", "numeric", "numeric"))
dim(dfZIPs)
```

```{r}
dfZIPs <- 
  dfZIPs %>% 
  dplyr::mutate( Geohash = geohashTools::gh_encode(latitude = LAT, longitude = LON, precision = 9) )
```

```{r}
dfZIPs %>% dplyr::sample_n(10)
```


Make a data frame of 300 hypothetical trips:

```{r}
set.seed(719)
dfRoutes <- data.frame( id = 1:400, start = sample(dfZIPs$ZIP, 400), end = sample(dfZIPs$ZIP, 400))
dfRoutes <- dfRoutes %>% dplyr::filter(start != end)
dfRoutes <- dfRoutes[1:300, ]
dim(dfRoutes)
```

Add the coordinates and make the data frame to have the expected column names:

```{r}
dfRoutes <- 
  dfRoutes %>% 
  dplyr::inner_join(dfZIPs, by = c("start" = "ZIP")) %>% 
  dplyr::rename( lat1 = LAT, lon1 = LON) %>% 
  dplyr::inner_join(dfZIPs, by = c("end" = "ZIP")) %>% 
  dplyr::rename( lat2 = LAT, lon2 = LON) %>% 
  dplyr::mutate( id = paste0(start, ":", end)) %>% 
  dplyr::select(id, lat1, lon1, lat2, lon2) %>% 
  dplyr::filter( -90 <= lat1 & lat1 <= 90 & -90 <= lat2 & lat2 <= 90 )
  
dfRoutes
```

---------

# Finding NNs

```{r}
geohashTools::gh_decode("9vf1") 
```

```{r}
grRoutes4 <- make_route_graph(precision = 4)

igraph::gorder(grRoutes4)
igraph::gsize(grRoutes4)
```
```{r}
matCoords <- purrr::map_df(igraph::V(grRoutes4)$name, function(x) { geohashTools::gh_decode(x) })
matCoords <- as.matrix(matCoords)
rownames(matCoords) <- igraph::V(grRoutes4)$name
matCoords[1:3,]
```
```{r}
system.time({
  
  lsMinPos <- purrr::map(1:100, function(i) {
    focusPoint <- matCoords[i,]
    matFocusPoint <- matrix(rep_len(x = focusPoint, length.out = 2*nrow(matCoords)), byrow = T, ncol = 2)
    lsDists <- sqrt(rowSums((matFocusPoint - matCoords) * (matFocusPoint - matCoords)))
    names(which.min(lsDists))
  })
  
})
```
